# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='name')),
                ('mail', models.EmailField(max_length=32, verbose_name='Email')),
                ('message', models.TextField(max_length=255, verbose_name='content')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
    ]
