# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvhang', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='KSinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
    ]
