# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvhang', '0003_ksinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KSinfo_ahks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_bjks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_fjks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_gsks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_gxks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_hbks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_hebks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_jsks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_jxks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_nmks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_shks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
        migrations.CreateModel(
            name='KSinfo_tjks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=36, verbose_name='date')),
                ('status', models.TextField(max_length=12, verbose_name='status')),
                ('hezhi', models.TextField(max_length=12, verbose_name='hezhi')),
                ('BigS', models.TextField(max_length=24, verbose_name='BigS')),
                ('SigD', models.TextField(max_length=24, verbose_name='SigD')),
            ],
        ),
    ]
